# Generated by Django 5.1.1 on 2024-09-11 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='date_fabrication',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prix_ht',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='code',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monapp.productstatus'),
        ),
    ]
