# Generated by Django 5.1.1 on 2024-10-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0003_productattribute_status_alter_product_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='color',
        ),
    ]
