# Generated by Django 5.1.1 on 2024-10-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0005_order_supplier_orderitem_productsupplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupplier',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantité en stock'),
        ),
    ]
