# Generated by Django 5.1.1 on 2024-10-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0006_productsupplier_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Image du produit'),
        ),
    ]
