# Generated by Django 5.1.1 on 2024-10-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0007_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='img/', verbose_name='Image du produit'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='product_item', to='monapp.productattributevalue'),
        ),
    ]
