# Generated by Django 5.1.1 on 2024-10-16 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0011_remove_order_product_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monapp.product'),
        ),
        migrations.CreateModel(
            name='SupplierSellProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire TTC')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.supplier')),
            ],
            options={
                'unique_together': {('product', 'supplier')},
            },
        ),
    ]
