# Generated by Django 5.1.1 on 2024-10-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0013_alter_cart_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mis_en_stock',
            field=models.BooleanField(default=False),
        ),
    ]
