# Generated by Django 5.1.1 on 2024-10-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0014_order_mis_en_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
