# Generated by Django 5.1.1 on 2024-10-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0016_remove_cart_created_at_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validatedcartitem',
            name='product_supplier',
        ),
        migrations.RemoveField(
            model_name='validatedcartitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='validatedcart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='validatedcartitem',
            name='cart_item',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
