# Generated by Django 5.1.1 on 2024-10-18 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0019_alter_validatedcartitem_cart_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validatedcartitem',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='validatedcartitem',
            name='product_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monapp.productsupplier'),
        ),
        migrations.AddField(
            model_name='validatedcartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
