# Generated by Django 5.1.1 on 2024-10-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0020_remove_validatedcartitem_cart_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='suppliers',
        ),
    ]
