# Generated by Django 5.1.1 on 2024-10-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0021_remove_product_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(related_name='suppliers', through='monapp.ProductSupplier', to='monapp.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, default='img/images.jpeg', upload_to='img/', verbose_name='Image du produit'),
        ),
    ]
